language: generic
sudo: required
services:
        - docker

before_install:
        - docker build -t amoldc/docker-react -f Dockerfile.dev .

script:
        - docker run -e CI=true amoldc/docker-react npm run test

